# Generated by Django 2.0.5 on 2020-07-29 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('email', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('employer', models.IntegerField()),
                ('full_name', models.CharField(max_length=60)),
            ],
        ),
    ]
