# Generated by Django 2.0.5 on 2020-08-12 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enpApi', '0003_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='email',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='playsession',
            name='date_taken',
            field=models.DateField(auto_now=True),
        ),
    ]
