# Generated by Django 2.0.5 on 2020-12-12 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enpApi', '0012_playsession_training_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='admin',
            field=models.BooleanField(default=False),
        ),
    ]
