# Generated by Django 2.0.5 on 2021-04-24 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enpApi', '0017_auto_20210423_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='registration_type',
            field=models.CharField(choices=[('Desktop', 'Desktop'), ('VR', 'VR')], max_length=255),
        ),
    ]
