# Generated by Django 2.0.5 on 2021-05-29 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enpApi', '0019_auto_20210424_1451'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moduledownloadlink',
            options={'ordering': ['training_type', 'platform_category']},
        ),
        migrations.AddField(
            model_name='playsession',
            name='date_modified',
            field=models.DateField(auto_now=True, verbose_name='date modified'),
        ),
    ]
