# Generated by Django 2.0.13 on 2021-02-04 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_resource'),
    ]

    operations = [
        migrations.CreateModel(
            name='DLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_type', models.CharField(default='', max_length=16)),
                ('supervisor', models.BooleanField(default=False)),
                ('link_address', models.CharField(max_length=128)),
            ],
        ),
    ]
