# Generated by Django 2.0.13 on 2021-05-02 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_dlinks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DLinks',
        ),
    ]
