# Generated by Django 4.1.1 on 2022-11-28 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_delete_dlinks'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkedinPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=250)),
            ],
        ),
    ]
