# Generated by Django 4.1.1 on 2022-11-28 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_linkedinpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedinpost',
            name='ub_date',
            field=models.DateTimeField(null=True, verbose_name='date published'),
        ),
    ]
