# Generated by Django 4.1.1 on 2022-11-28 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_linkedinpost_ub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedinpost',
            name='height',
            field=models.IntegerField(default=639),
        ),
        migrations.AddField(
            model_name='linkedinpost',
            name='width',
            field=models.IntegerField(default=371),
        ),
    ]
