# Generated by Django 4.1.1 on 2022-11-28 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_linkedinpost_height_linkedinpost_width'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkedinpost',
            name='height',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='linkedinpost',
            name='width',
            field=models.IntegerField(),
        ),
    ]
