# Generated by Django 4.1.1 on 2022-11-28 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_linkedinpost_height_alter_linkedinpost_width'),
    ]

    operations = [
        migrations.RenameField(
            model_name='linkedinpost',
            old_name='ub_date',
            new_name='pub_date',
        ),
    ]
