# Generated by Django 4.1.1 on 2022-12-02 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_rename_ub_date_linkedinpost_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediumPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_m', models.CharField(max_length=250)),
                ('Summary_m', models.CharField(max_length=374)),
                ('pub_date_m', models.DateTimeField(null=True, verbose_name='date published')),
                ('title_m', models.CharField(max_length=100)),
            ],
        ),
    ]
