# Generated by Django 4.1.1 on 2022-12-02 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_mediumpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediumpost',
            name='photo',
            field=models.ImageField(null=True, upload_to='medium'),
        ),
    ]
