# Generated by Django 4.1.1 on 2022-12-02 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_mediumpost_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mediumpost',
            old_name='photo',
            new_name='m_photo',
        ),
    ]
