# Generated by Django 4.1.1 on 2022-12-02 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_rename_photo_mediumpost_m_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediumpost',
            name='m_photo',
            field=models.ImageField(null=True, upload_to='blog/medium/photos'),
        ),
    ]
