# Generated by Django 2.0.5 on 2024-06-07 16:25

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_mediumpost_m_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediumpost',
            name='m_photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
