# Generated by Django 2.0.5 on 2022-12-29 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_mediumpost_m_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediumpost',
            name='m_photo',
            field=models.ImageField(null=True, upload_to='media/medium/photos'),
        ),
    ]
