# Generated by Django 2.2.24 on 2025-04-04 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20240607_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkedinpost',
            name='height',
        ),
        migrations.RemoveField(
            model_name='linkedinpost',
            name='width',
        ),
    ]
