# Generated by Django 2.0.5 on 2023-09-05 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20230804_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_p', models.CharField(max_length=250)),
                ('Summary_p', models.CharField(max_length=374)),
                ('pub_date_p', models.DateTimeField(null=True, verbose_name='date published')),
                ('title_p', models.CharField(max_length=100)),
                ('p_photo', models.ImageField(null=True, upload_to='press/photos')),
            ],
        ),
        migrations.AlterField(
            model_name='mediumpost',
            name='m_photo',
            field=models.ImageField(null=True, upload_to='medium/photos'),
        ),
    ]
