# Generated by Django 2.0.5 on 2022-12-29 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20221229_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediumpost',
            name='m_photo',
            field=models.ImageField(null=True, upload_to='medium/photos'),
        ),
    ]
