# Generated by Django 2.0.5 on 2023-02-28 02:01

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20221229_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediumpost',
            name='m_photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
