# Generated by Django 2.2.24 on 2025-04-04 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20250404_0143'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedinpost',
            name='height',
            field=models.IntegerField(blank=True, default=500, null=True),
        ),
        migrations.AddField(
            model_name='linkedinpost',
            name='width',
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
    ]
