# Generated by Django 2.2.24 on 2025-04-04 03:57

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20250404_0146'),
    ]

    operations = [
        migrations.CreateModel(
            name='PressArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_title', models.CharField(max_length=200)),
                ('p_url', models.URLField()),
                ('p_summary', models.TextField(max_length=500)),
                ('p_photo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('pub_date', models.DateTimeField(blank=True, null=True, verbose_name='date published')),
            ],
        ),
    ]
