# Generated by Django 2.0.5 on 2023-05-08 18:48

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20230504_2144'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pres',
        ),
        migrations.AlterField(
            model_name='mediumpost',
            name='m_photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
