# Generated by Django 2.0.5 on 2021-06-22 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=60)),
                ('employer_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('employer', models.IntegerField()),
                ('email', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='LoginSessions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('date_logged_in', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModuleDownloadLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_type', models.CharField(choices=[('Desktop', 'Desktop'), ('VR', 'VR')], max_length=255)),
                ('training_category', models.CharField(choices=[('None', 'None'), ('Harassment Training', 'Harassment Training')], max_length=255)),
                ('platform_category', models.CharField(choices=[('Windows', 'Windows'), ('Mac', 'Mac'), ('SteamVR', 'SteamVR'), ('Oculus Quest', 'Oculus Quest')], max_length=255)),
                ('download_link', models.CharField(max_length=554)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('is_supervisor', models.BooleanField()),
            ],
            options={
                'ordering': ['training_type', 'platform_category'],
            },
        ),
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('case', models.IntegerField()),
                ('creation_date', models.DateField()),
                ('is_available', models.BooleanField(default=False)),
                ('is_mandatory', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PassWordKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=20)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('email', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('employer', models.IntegerField()),
                ('full_name', models.CharField(max_length=60)),
                ('supervisor', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('registration_type', models.CharField(default='', max_length=16)),
                ('has_signed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlaySession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer', models.IntegerField()),
                ('module_id', models.IntegerField()),
                ('date_taken', models.DateField(auto_now=True)),
                ('score', models.IntegerField()),
                ('success', models.BooleanField()),
                ('time_taken', models.IntegerField()),
                ('training_type', models.CharField(default='', max_length=16)),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='enpApi.Player')),
            ],
        ),
        migrations.CreateModel(
            name='RegKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=20)),
                ('supervisor', models.BooleanField()),
                ('training_type', models.CharField(default='', max_length=16)),
                ('company_name', models.CharField(default='', max_length=60)),
                ('training_duration', models.IntegerField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
