# Generated by Django 2.0.5 on 2020-07-29 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enpApi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('case', models.IntegerField()),
                ('creation_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PlaySession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_email', models.CharField(max_length=30)),
                ('module_id', models.IntegerField()),
                ('date_taken', models.DateField()),
                ('score', models.IntegerField()),
                ('success', models.BooleanField()),
            ],
        ),
    ]
