# Generated by Django 2.0.5 on 2020-08-12 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enpApi', '0004_auto_20200812_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='playsession',
            name='time_taken',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
