# Generated by Django 2.0.13 on 2020-10-24 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enpApi', '0006_player_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='playsession',
            name='employer',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
