# Generated by Django 2.0.13 on 2020-10-24 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enpApi', '0007_playsession_employer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playsession',
            name='employee_email',
        ),
        migrations.AddField(
            model_name='playsession',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='enpApi.Player'),
        ),
    ]
