# Generated by Django 2.0.13 on 2020-10-25 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enpApi', '0008_auto_20201024_0713'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='supervisor',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
