# Generated by Django 2.0.5 on 2020-11-22 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enpApi', '0010_invite_loginsessions'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='has_signed',
            field=models.BooleanField(default=False),
        ),
    ]
