# Generated by Django 2.0.13 on 2020-12-24 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enpApi', '0011_auto_20201222_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='supervisor',
            field=models.BooleanField(default=False),
        ),
    ]
