# Generated by Django 2.0.5 on 2020-12-07 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enpApi', '0011_player_has_signed'),
    ]

    operations = [
        migrations.AddField(
            model_name='playsession',
            name='training_type',
            field=models.CharField(default='', max_length=16),
        ),
    ]
