# Generated by Django 2.0.13 on 2020-12-24 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enpApi', '0012_auto_20201224_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='playsession',
            name='employee_email',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='playsession',
            name='employer',
            field=models.IntegerField(default=0),
        ),
    ]
