# Generated by Django 2.0.13 on 2021-01-13 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enpApi', '0013_auto_20201224_0155'),
        ('enpApi', '0014_player_registration_type'),
    ]

    operations = [
    ]
