# Generated by Django 2.0.13 on 2021-01-30 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enpApi', '0015_merge_20210113_0112'),
    ]

    operations = [
    ]
