# Generated by Django 2.0.5 on 2021-04-23 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enpApi', '0015_moduledownloadlinks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ModuleDownloadLinks',
            new_name='ModuleDownloadLink',
        ),
    ]
