# Generated by Django 2.0.5 on 2021-04-23 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enpApi', '0016_auto_20210423_1516'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moduledownloadlink',
            old_name='category',
            new_name='training_category',
        ),
        migrations.AddField(
            model_name='moduledownloadlink',
            name='platform_category',
            field=models.CharField(choices=[('Desktop Windows', 'Desktop Windows'), ('Desktop Mac', 'Desktop Mac'), ('SteamVR', 'SteamVR'), ('Oculus Quest', 'Oculus Quest')], default=1, max_length=255),
            preserve_default=False,
        ),
    ]
