# Generated by Django 2.0.13 on 2021-02-05 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enpApi', '0016_auto_20210130_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='modules',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='modules',
            name='is_mandatory',
            field=models.BooleanField(default=False),
        ),
    ]
