# Generated by Django 2.0.13 on 2021-02-10 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enpApi', '0017_auto_20210205_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='supervisor',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='playsession',
            name='employer',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='playsession',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='enpApi.Player'),
        ),
    ]
