# Generated by Django 2.0.13 on 2021-03-08 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enpApi', '0018_auto_20210210_0122'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=80)),
            ],
        ),
    ]
