# Generated by Django 2.0.5 on 2021-04-24 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enpApi', '0018_auto_20210424_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='moduledownloadlink',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='moduledownloadlink',
            name='platform_category',
            field=models.CharField(choices=[('Windows', 'Windows'), ('Mac', 'Mac'), ('SteamVR', 'SteamVR'), ('Oculus Quest', 'Oculus Quest')], max_length=255),
        ),
    ]
