# Generated by Django 2.0.5 on 2021-05-29 22:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('enpApi', '0020_auto_20210529_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='playsession',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date created'),
            preserve_default=False,
        ),
    ]
