# Generated by Django 2.0.5 on 2021-06-06 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enpApi', '0021_moduledownloadlink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playsession',
            name='employee_email',
        ),
        migrations.AddField(
            model_name='employer',
            name='employer_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
