# Generated by Django 2.0.5 on 2021-06-17 01:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('enpApi', '0022_auto_20210606_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adjective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adj_id', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
                ('creation_date', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ComparisonRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comparison_rating_id', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
                ('creation_date', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostProgramSurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_experience', models.IntegerField()),
                ('overall_experience_feedback', models.TextField(blank=True, max_length=3000, null=True)),
                ('comments', models.TextField(blank=True, max_length=3000, null=True)),
                ('contact', models.TextField(blank=True, max_length=3000, null=True)),
                ('has_completed', models.BooleanField(default=False)),
                ('creation_date', models.DateField(auto_now_add=True, null=True)),
                ('comparison_rating_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='enpApi.ComparisonRating')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SelectedAdjective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(auto_now_add=True, null=True)),
                ('adj_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='enpApi.Adjective')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
