# Generated by Django 2.0.5 on 2021-06-21 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enpApi', '0023_adjective_comparisonrating_postprogramsurvey_selectedadjective'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postprogramsurvey',
            old_name='overall_experience_feedback',
            new_name='overall_feedback',
        ),
        migrations.RenameField(
            model_name='postprogramsurvey',
            old_name='overall_experience',
            new_name='overall_rating',
        ),
    ]
