# Generated by Django 2.0.5 on 2021-06-25 04:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('enpApi', '0025_auto_20210621_1923'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostProgramSurveySupervisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommend_friend_scale', models.IntegerField()),
                ('overall_feedback', models.TextField(blank=True, max_length=3000, null=True)),
                ('info_retention_scale', models.IntegerField()),
                ('confidence_scale', models.IntegerField()),
                ('recommend_manager_scale', models.IntegerField()),
                ('recommend_employee_scale', models.IntegerField()),
                ('comments', models.TextField(blank=True, max_length=3000, null=True)),
                ('has_completed', models.BooleanField(default=False)),
                ('creation_date', models.DateField(auto_now_add=True, null=True)),
                ('comparison_rating_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='enpApi.ComparisonRating')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
