# Generated by Django 2.0.5 on 2021-06-25 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enpApi', '0026_postprogramsurveysupervisor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postprogramsurveysupervisor',
            old_name='overall_feedback',
            new_name='recommend_friend_reason',
        ),
    ]
