# Generated by Django 2.0.5 on 2021-07-14 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enpApi', '0027_auto_20210625_0432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='employer_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='supervisor',
            field=models.BooleanField(default=False),
        ),
    ]
