# Generated by Django 2.0.5 on 2021-07-14 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enpApi', '0028_auto_20210714_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postprogramsurveysupervisor',
            name='confidence_scale',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='postprogramsurveysupervisor',
            name='info_retention_scale',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='postprogramsurveysupervisor',
            name='recommend_employee_scale',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='postprogramsurveysupervisor',
            name='recommend_friend_scale',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='postprogramsurveysupervisor',
            name='recommend_manager_scale',
            field=models.IntegerField(null=True),
        ),
    ]
