# Generated by Django 2.0.5 on 2021-07-26 21:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('enpApi', '0029_auto_20210714_0041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Behavior',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('behavior_id', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
                ('creation_date', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EthicalFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=255)),
                ('scene', models.IntegerField()),
                ('emotion', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('behavior_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='enpApi.Behavior')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=255)),
                ('scene', models.IntegerField()),
                ('role', models.CharField(max_length=255)),
            ],
        ),
    ]
