# Generated by Django 2.0.5 on 2021-08-30 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enpApi', '0029_auto_20210714_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_provisional',
            field=models.BooleanField(default=True),
        ),
    ]
