# Generated by Django 2.0.5 on 2021-09-20 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enpApi', '0030_behavior_ethicalfeedback_playerrole'),
    ]

    operations = [
        migrations.CreateModel(
            name='SceneInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=255)),
                ('scene', models.IntegerField()),
                ('is_required', models.BooleanField(default=True)),
                ('player_role', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='PlayerRole',
        ),
    ]
