# Generated by Django 2.0.5 on 2021-10-20 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enpApi', '0031_sceneInfo_20210920_2207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sceneinfo',
            old_name='is_required',
            new_name='is_mandatory',
        ),
        migrations.AddField(
            model_name='sceneinfo',
            name='ethical_npc_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sceneinfo',
            name='ethical_screenshot',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='sceneinfo',
            name='ethical_script',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
