# Generated by Django 2.0.5 on 2021-09-20 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enpApi', '0031_sceneInfo_20210920_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='sceneinfo',
            name='ethical_npc_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sceneinfo',
            name='ethical_screenshot',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='sceneinfo',
            name='ethical_script',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
    ]
