# Generated by Django 2.0.5 on 2021-10-20 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enpApi', '0030_player_is_provisional'),
        ('enpApi', '0032_sceneInfo_addFieldsForScreenshots'),
    ]

    operations = [
    ]
