# Generated by Django 2.0.5 on 2021-11-15 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enpApi', '0035_addFields_mandatoryModules'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='creation_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='training_deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
