# Generated by Django 2.0.5 on 2021-11-15 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enpApi', '0036_addFields_playerDueDate'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingPackageDownloadLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_type', models.CharField(choices=[('Desktop', 'Desktop'), ('VR', 'VR')], max_length=255)),
                ('training_category', models.CharField(choices=[('None', 'None'), ('Harassment Training', 'Harassment Training')], max_length=255)),
                ('platform_category', models.CharField(choices=[('Windows', 'Windows'), ('Mac', 'Mac'), ('SteamVR', 'SteamVR'), ('Oculus Quest', 'Oculus Quest')], max_length=255)),
                ('download_link', models.CharField(max_length=554)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('size', models.CharField(blank=True, default='1.2GB', max_length=10, null=True)),
                ('is_supervisor', models.BooleanField()),
            ],
            options={
                'ordering': ['training_type', 'platform_category'],
            },
        ),
        migrations.DeleteModel(
            name='ModuleDownloadLink',
        ),
    ]
