# Generated by Django 2.0.5 on 2021-11-15 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enpApi', '0037_renameModel_trainingPackageDownload'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupervisorMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(auto_now_add=True, null=True)),
                ('modification_date', models.DateField(auto_now=True, null=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_member', to='enpApi.Player')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_supervisor', to='enpApi.Player')),
            ],
            options={
                'ordering': ['supervisor'],
            },
        ),
    ]
