# Generated by Django 2.0.5 on 2021-11-15 23:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enpApi', '0038_create_supervisormapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisormapping',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_member', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='supervisormapping',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_supervisor', to=settings.AUTH_USER_MODEL),
        ),
    ]
