# Generated by Django 2.0.5 on 2021-12-05 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enpApi', '0040_addFields_allModules'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modules',
            old_name='code',
            new_name='module_id',
        ),
        migrations.RemoveField(
            model_name='ethicalfeedback',
            name='module',
        ),
        migrations.RemoveField(
            model_name='sceneinfo',
            name='module',
        ),
        migrations.AddField(
            model_name='ethicalfeedback',
            name='module_id',
            field=models.CharField(default='na', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sceneinfo',
            name='module_id',
            field=models.CharField(default='na', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='playsession',
            name='module_id',
            field=models.CharField(max_length=10),
        ),
    ]
