# Generated by Django 2.0.5 on 2021-12-06 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enpApi', '0041_char_moduleid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modules',
            name='case',
        ),
        migrations.RemoveField(
            model_name='modules',
            name='is_mandatory',
        ),
        migrations.AlterField(
            model_name='employer',
            name='mandatory_modules',
            field=models.ManyToManyField(blank=True, related_name='mandatory_modules', to='enpApi.Modules'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='registered_modules',
            field=models.ManyToManyField(blank=True, related_name='all_modules', to='enpApi.Modules'),
        ),
        migrations.AlterField(
            model_name='selectedadjective',
            name='adj_id',
            field=models.ManyToManyField(to='enpApi.Adjective'),
        ),
    ]
