# Generated by Django 2.0.5 on 2022-11-21 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enpApi', '0042_auto_20211206_0444'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='provisioned_modules',
            field=models.ManyToManyField(blank=True, related_name='provisioned_modules', to='enpApi.Modules'),
        ),
    ]
