# Generated by Django 2.0.5 on 2021-12-20 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enpApi', '0042_auto_20211206_0444'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=60)),
                ('creation_date', models.DateField(auto_now_add=True, null=True)),
                ('modification_date', models.DateField(auto_now=True, null=True)),
                ('employer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='enpApi.Employer')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(auto_now_add=True, null=True)),
                ('modification_date', models.DateField(auto_now=True, null=True)),
            ],
            options={
                'ordering': ['team'],
            },
        ),
        migrations.AddField(
            model_name='player',
            name='modification_date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='teammapping',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='enpApi.Player'),
        ),
        migrations.AddField(
            model_name='teammapping',
            name='team',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='enpApi.Team'),
        ),
        migrations.AddField(
            model_name='team',
            name='leader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='enpApi.Player'),
        ),
    ]
