# Generated by Django 2.0.5 on 2021-12-13 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enpApi', '0042_auto_20211206_0444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postprogramsurvey',
            name='user',
        ),
        migrations.RemoveField(
            model_name='postprogramsurveysupervisor',
            name='user',
        ),
        migrations.RemoveField(
            model_name='selectedadjective',
            name='user',
        ),
        migrations.AddField(
            model_name='postprogramsurvey',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='enpApi.Player'),
        ),
        migrations.AddField(
            model_name='postprogramsurveysupervisor',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='enpApi.Player'),
        ),
        migrations.AddField(
            model_name='selectedadjective',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='enpApi.Player'),
        ),
    ]
