# Generated by Django 2.0.5 on 2022-11-21 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enpApi', '0043_player_provisioned_modules'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='provisioned_modules',
        ),
    ]
