# Generated by Django 2.0.5 on 2021-12-20 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enpApi', '0043_auto_20211220_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammapping',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='enpApi.Team'),
        ),
    ]
