# Generated by Django 2.0.5 on 2023-03-14 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enpApi', '0044_remove_player_provisioned_modules'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer', models.IntegerField()),
                ('module_id', models.CharField(max_length=10)),
                ('currrent_scene', models.CharField(max_length=30)),
                ('time_taken', models.IntegerField()),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='enpApi.Player')),
            ],
        ),
    ]
