# Generated by Django 2.0.5 on 2023-04-07 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enpApi', '0046_auto_20230314_2015'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('device_model', models.CharField(max_length=10)),
                ('date_taken', models.DateField(auto_now=True)),
                ('sisu_user', models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='playsession',
            name='time_taken',
        ),
    ]
