# Generated by Django 2.0.5 on 2023-04-07 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enpApi', '0047_auto_20230407_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usagereport',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
