# Generated by Django 2.0.5 on 2023-08-04 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enpApi', '0049_auto_20230407_0356'),
    ]

    operations = [
        migrations.AddField(
            model_name='usagereport',
            name='ip_address',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usagereport',
            name='module_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
