# Generated by Django 2.0.5 on 2024-06-07 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enpApi', '0049_auto_20230407_0356'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaySessionMG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer', models.IntegerField()),
                ('module_id', models.CharField(max_length=10)),
                ('date_taken', models.DateField(auto_now=True)),
                ('score', models.IntegerField()),
                ('success', models.BooleanField()),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='enpApi.Player')),
            ],
        ),
        migrations.CreateModel(
            name='PlayStateMG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer', models.IntegerField()),
                ('module_id', models.CharField(max_length=10)),
                ('current_scene', models.CharField(max_length=30)),
                ('time_taken', models.IntegerField()),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='enpApi.Player')),
            ],
        ),
    ]
