# Generated by Django 2.0.5 on 2024-07-10 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enpApi', '0050_playsessionmg_playstatemg'),
    ]

    operations = [
        migrations.AddField(
            model_name='usagereport',
            name='ip_address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usagereport',
            name='module_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
