# Generated by Django 2.0.13 on 2020-11-06 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enpApi', '0009_player_supervisor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('employer', models.IntegerField()),
                ('email', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='LoginSessions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('date_logged_in', models.DateField(auto_now=True)),
            ],
        ),
    ]
